# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30325d13c95af5aae8571d424e8957da56fee9dc0846d51a679dc15dec91100b849dc3ab8fb6f778f47cf90908e7ab8bf1115e778b2ee5d281e43f652bb20b12

test:
  secret_key_base: 061555557e77e7bcf737153e144cb68176027b462150710e7c6e8bd2fa9eb322787827e03fb7ca549aafac793645690fda2b17861078fe0337e2dbace7e7e71c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
